### ISSUE TITLE
Question: Where to investigate for the "Dead Night" task given by Sidor?

### ISSUE THREAD

**Issue by Phoenix1297** [lTheon/iTheon-New-Tasks-Addon#24]
I am posting this here as there's no ModDB page for this.
For the Dead Night task obtained from Sidor, I ran across roughly the entire Darkscape map at night (10 PM - 3 AM) and still can't figure out what/where to look for. Could you please help me with this?

P.S. I absolutely LOVE these new tasks! House of Horrors is the crown jewel of this addon.

**Comment by lTheon** [comment]
Hey there
You're not the only person that had issues with it
Here's where the task script fires (cursor position)
![Screenshot (116)](https://github.com/user-attachments/assets/d2b98a70-5734-4d5a-8759-876ab2bbc6ba)

I didn't want to add a quest marker there to not make it too obvious and keep the element of surprise
I might need to think of a way to attract the player to this place somehow... maybe add some noises or something

**Comment by Phoenix1297** [comment]
> Hey there You're not the only person that had issues with it Here's where the task script fires (cursor position) ![Screenshot (116)](https://private-user-images.githubusercontent.com/35302307/368646507-d2b98a70-5734-4d5a-8759-876ab2bbc6ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzU3MjAsIm5iZiI6MTcyNjY3NTQyMCwicGF0aCI6Ii8zNTMwMjMwNy8zNjg2NDY1MDctZDJiOThhNzAtNTczNC00ZDVhLTg3NTktODc2YWIyYmJjNmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDE2MDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZWFiOTBjOGQ3ODA2NDIyNTZmYmVmYzY5NTJhZWZkOGEwMWE5Yjk3ZGVhMjc4YTIzYWM3YTIwYjE5OWY2YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._62hFXQwc3mNpyokq42ld8-aW5CQAyrktelxmsbPfVE)
> 
> I didn't want to add a quest marker there to not make it too obvious and keep the element of surprise I might need to think of a way to attract the player to this place somehow... maybe add some noises or something

Thanks a lot! Yeah, I think adding noises is a good idea. House of Horrors executes this perfectly.
